/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cc10;

import java.util.Stack;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws Exception {
        System.out.println(new App().getGreeting());
        Stack<Integer> stackList = new Stack<>();
        stackList.push(2);
        stackList.push(1);
        stackList.push(8);
        stackList.push(10);

        System.out.println(" ============ Stack =========== ");
        System.out.println("Our List :" + stackList);
        System.out.println("Is our list empty? " + stackList.isEmpty());
        System.out.println("If we remove the head : " + stackList.pop());
        System.out.println("Top New value is : " + stackList.peek());
        System.out.println("Our New List :" + stackList);

        /* ----------------------------------------------------------- */

        Queue<String> queueList = new Queue<>();
        queueList.enqueue("2");
        queueList.enqueue("1");
        queueList.enqueue("8");
        queueList.enqueue("10");

        System.out.println(" ============ Queue =========== ");
        System.out.println("Our List :" + queueList);
        System.out.println("Is our list empty? " + queueList.isEmpty());
        System.out.println("If we remove the head : " + queueList.dequeue());
        System.out.println("Top New value is : " + queueList.peek());
        System.out.println("Our New List :" + queueList);
        System.out.println(" ============================= ");
    }
    }

