/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quick.sort;

import java.util.Arrays;

import static quick.sort.QuickSort.quickSort;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        int[] arr = { 8,4,23,42,16,15};
        int j = arr.length;
        QuickSort quickSort2= new QuickSort();
        quickSort(arr, 0, j - 1);
        System.out.println(Arrays.toString(quickSort(arr, 0, arr.length-1)));
    }
}
