/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package trees;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        BinaryTree<Integer> newTree = new BinaryTree<>();
        Node<Integer> node5 = new Node<>(6);


        BinarySearchTree binarySearchTree = new BinarySearchTree();
        Node<Integer> searchNodeOne = new Node<>(15);
        Node<Integer> searchNodeThree = new Node<>(10);

        binarySearchTree.add(27);
        binarySearchTree.add(26);

        binarySearchTree.contains(7);
        System.out.println (binarySearchTree.contains(14));

    }


}
