/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package stack.and.queue;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {

        System.out.println(new App().getGreeting());
        Stack <Integer> stack = new Stack<>();
        stack.push(11);
        stack.push(50);
        System.out.println(stack.peek());
        Queue <Integer> queue = new Queue<>();
        System.out.println(queue.rear.value);
        queue.enqueue(2);
    }
}
