/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package code30hashtable;

import java.util.Hashtable;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
  Hashtable hashtable = new Hashtable();

        hashtable.contains(1);



    }
}
