/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package code30hashtable;

import java.util.*;
import java.util.Hashtable;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
  Hashtable hashtable = new Hashtable();

        hashtable.contains(1);





    }
    public static Map<String,
            List<String>> hashMapLeftJoins(Map<String,String> map1, Map<String,String> map2){
        Map<String,List<String>> result=new HashMap<>();
        System.out.println(map1);
        System.out.println(map2);
        map1.forEach((key,value)->{
            result.put(key, Arrays.asList(value, map2.getOrDefault(value, "null")));
        });
        System.out.println(result);

        return result;

    }


}
