/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package challeng06;


import org.w3c.dom.Node;

import java.util.LinkedList;

public class App {

    public static void main(String[] args) {

        LinkedList myList = new LinkedList();
        myList.append(1);
        myList.append(2);
        myList.append(3);
        myList.append(4);
        myList.append(5);
        myList.append(6);

        myList.insertAfter(4,10);
        myList.insertBefore(1,10);

        Node current = myList.head;
        while (current != null) {
            System.out.println(current.value);
            current = current.next;
        }

        System.out.println(myList.includes(5));
        System.out.println(myList.includes(3));
        System.out.println(myList.includes(8));
        System.out.println(myList.includes(10));

        System.out.println(myList.toString());
    }
}